# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/diffusion_model_test',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/diffusion_model_test',
                'lib_path': 'diffusion_model_test'},
  'syms': {'diffusion_model_test.core': {'diffusion_model_test.core.foo': ('core.html#foo', 'diffusion_model_test/core.py')}}}
